### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ultrahacker678** [0x802/MikrotikSploit#2]
After setup.py install, there are an error
error: file '/data/data/com.termux/files/home/MikrotikSploit/MikrotikSploit' does not exist
![Screenshot_20210927-101458_Termux](https://user-images.githubusercontent.com/55056545/134861792-8b3a2ed2-81f4-4e9e-a257-9d690e4e68bd.jpg)

**Comment by 0x802** [comment]
hi bro
I delete setup.py ,cos the script will only work in the original path,
just run : python3 MikrotikSploit.py
